sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (player3, bat) {
    bat.destroy()
    info.changeLifeBy(-1)
})
let enemy: Sprite = null
let player2 = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(player2)
info.setLife(3)
tiles.setTilemap(tilemap`level`)
game.onUpdateInterval(2000, function () {
    enemy = sprites.create(img`
        . . f f f . . . . . . . . . . .
        f f f c c . . . . . . . . f f f
        f f c c . . c c . . . f c b b c
        f f c 3 c c 3 c c f f b b b c .
        f f b 3 b c 3 b c f b b c c c .
        . c b b b b b b c f b c b c c .
        . c b b b b b b c b b c b b c .
        c b 2 b b b 2 b b b c c c b c .
        c b b b b b b b b c c c c c . .
        f b c b b b c b b b b f c . . .
        f b 1 f f f 1 b b b b f c c . .
        . f 2 b b b 2 b b b c f . . . .
        . . 2 b b b 2 2 b c f . . . . .
        . . . f f f f 2 f f . . . . . .
        . . . . . . . 2 . . . . . . . .
        . . . . . . . . . . . . . . . .
    `, SpriteKind.Enemy)
    enemy.setFlag(SpriteFlag.AutoDestroy, true)
    enemy.setPosition(160, randint(0, 120))
    enemy.setVelocity(-50, 0)
})
